import type { RoverLevel, RoverLevelConfig } from '../types';

const publicAsset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`;

export const roverLevels: readonly RoverLevelConfig[] = [
  {
    level: 1,
    id: 'courier',
    title: 'Курьер',
    assetPath: publicAsset('assets/games/rovers/rover-01-courier-render.webp'),
    physicsRadius: 27,
    renderSize: 62,
    scoreValue: 0,
    displayScale: 1,
    offsetY: -1,
    sourceCrop: { x: 0, y: 0, width: 981, height: 1000 },
  },
  {
    level: 2,
    id: 'cleaner',
    title: 'Уборщик',
    assetPath: publicAsset('assets/games/rovers/rover-02-cleaner-render.webp'),
    physicsRadius: 33,
    renderSize: 74,
    scoreValue: 10,
    displayScale: 1,
    sourceCrop: { x: 0, y: 0, width: 865, height: 934 },
  },
  {
    level: 3,
    id: 'cargo',
    title: 'Грузовой',
    assetPath: publicAsset('assets/games/rovers/rover-03-cargo-render.webp'),
    physicsRadius: 40,
    renderSize: 88,
    scoreValue: 25,
    displayScale: 1,
    offsetY: 1,
    sourceCrop: { x: 0, y: 0, width: 982, height: 1015 },
  },
  {
    level: 4,
    id: 'repair',
    title: 'Ремонтник',
    assetPath: publicAsset('assets/games/rovers/rover-04-repair-render.webp'),
    physicsRadius: 48,
    renderSize: 104,
    scoreValue: 55,
    displayScale: 0.98,
    offsetX: 1,
    offsetY: 1,
    sourceCrop: { x: 0, y: 0, width: 1007, height: 924 },
  },
  {
    level: 5,
    id: 'food',
    title: 'Фуд-ровер',
    assetPath: publicAsset('assets/games/rovers/rover-05-food-render.webp'),
    physicsRadius: 57,
    renderSize: 122,
    scoreValue: 110,
    displayScale: 0.98,
    sourceCrop: { x: 0, y: 0, width: 899, height: 955 },
  },
  {
    level: 6,
    id: 'scanner',
    title: 'Сканер',
    assetPath: publicAsset('assets/games/rovers/rover-06-scanner-render.webp'),
    physicsRadius: 67,
    renderSize: 142,
    scoreValue: 220,
    displayScale: 0.98,
    offsetY: 1,
    sourceCrop: { x: 0, y: 0, width: 863, height: 966 },
  },
  {
    level: 7,
    id: 'speed',
    title: 'Экспресс',
    assetPath: publicAsset('assets/games/rovers/rover-07-speed-render.webp'),
    physicsRadius: 78,
    renderSize: 164,
    scoreValue: 450,
    displayScale: 0.97,
    sourceCrop: { x: 0, y: 0, width: 872, height: 859 },
  },
  {
    level: 8,
    id: 'legendary',
    title: 'Легендарный',
    assetPath: publicAsset('assets/games/rovers/rover-08-legendary-render.webp'),
    physicsRadius: 90,
    renderSize: 190,
    scoreValue: 900,
    displayScale: 0.96,
    offsetY: 2,
    sourceCrop: { x: 0, y: 0, width: 1003, height: 978 },
  },
] as const;

export function getRoverLevel(level: RoverLevel): RoverLevelConfig {
  return roverLevels[level - 1];
}
